
"""Update field id as uuid

Revision ID: 3df43800505e
Revises: 4387d5b6bbbd
Create Date: 2024-08-19 00:56:45.803782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df43800505e'
down_revision: Union[str, None] = '4387d5b6bbbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('uuid', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'uuid')
    # ### end Alembic commands ###
