"""Database creation

Revision ID: a7776d61d7ec
Revises: 
Create Date: 2024-08-16 10:16:10.728878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7776d61d7ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('download_task_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('accession_list', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
